@startuml


interface IFactoryable {
	+{abstract} create(const char operation) : IOperationable*
}


interface IOperationable {
	+{abstract} lastOperation() : char
	+{abstract} execute(const double leftOperand, const double rightOperand) : double
}

class OperationFactory {
    +IFactoryable factory
	+OperationFactory_Init()
	+create(const char operation) : IOperationable*
}

class NullOperation {
	+lastOperation() : char
	+execute(const double leftOperand, const double rightOperand) : double
}

/' Objects '/

class Calculator {
    +IFactoryable* factory
    -this : Calculator*
	+Calculator_Init(Calculator*const self, IFactoryable* factory)
	+GetLastOperation() : char
	+Calculate(const char operation, const double left_operand, const double right_operand) : double
}


class DivideOperation {
	+DivideOperation_Init(DivideOperation*const self)
	+operation : IOperationable
	-this : DivideOperation*
	-lastOperation() : char
	-execute(const double leftOperand, const double rightOperand) : double
}

class MinusOperation {
	+MinusOperation_Init(MinusOperation*const self)
	+operation : IOperationable
	-this : MinusOperation*
	-lastOperation() : char
	-execute(const double leftOperand, const double rightOperand) : double
}


class MultiplyOperation {
	+MultiplyOperation_Init(MultiplyOperation*const self)
	+operation : IOperationable
	-this : MultiplyOperation*
	-lastOperation() : char
	-execute(const double leftOperand, const double rightOperand) : double
}


class PlusOperation {
	+PlusOperation_Init(PlusOperation*const self)
	+operation : IOperationable
	-this : PlusOperation*
	-lastOperation() : char
	-execute(const double leftOperand, const double rightOperand) : double
}


/' Inheritance relationships '/

IFactoryable <|-- OperationFactory


IOperationable <|-- DivideOperation


IOperationable <|-- MinusOperation


IOperationable <|-- MultiplyOperation


IOperationable <|-- NullOperation


IOperationable <|-- PlusOperation





/' Aggregation relationships '/

Calculator -> IFactoryable : uses


OperationFactory .> IOperationable : creates





@enduml
